### ISSUE TITLE
R script

### ISSUE THREAD

**Issue by mbanco** [kreutz-lab/Rcall#1]
Hi,
Is it possible to run a full R script with Rcall?

Regards,

Mauricio

**Comment by JanineEgert** [comment]
Hi Mauricio,
yes it is possible to get your R code from an existing file. The function 'Rread' reads the lines of code and forwards it to the Rrun.R script accordingly. So the usual approach would be:
Rinit
Rpush('data',data)
Rread('Rscript.R')
result = Rpull('result')
Rclear

Best,
Janine

**Comment by mbanco** [comment]
Excellent Job!

Thank you Janine.

**Comment by JanineEgert** [comment]
Great I could help.
