### ISSUE TITLE
eval(['Rrun(''' linetext{i}(1:end-1) ''')']); shall be eval(['Rrun(''' linetext{i}(1:end) ''')']);?

### ISSUE THREAD

**Issue by canyi-chen** [kreutz-lab/Rcall#11]

**Comment by canyi-chen** [comment]
In the Rrunfile.m file.

**Comment by clemenskreutz** [comment]
Dear Canyi-Chen.
Thanks for pointing out that there might be a problem. 
I wrote a new version of the function. Should work now reliably.
Best, Clemens.
