### ISSUE TITLE
ERROR:The system cannot find the path specified. 

### ISSUE THREAD

**Issue by foudasarah** [kreutz-lab/Rcall#2]
Hello, 
I having the following issue when I'm making run the example script. 
I should have set all the path correctly maybe I missed something can you help? Thank you 

The system cannot find the path specified. 
The system cannot find the path specified. 
Warning: Is the R package installed? Try to run Rrun.R in R
for error prouning. 
> In Rpull (line 51) 
Unrecognized function or variable 'dat'.

Error in Rpull (line 56)
    if isfield(dat,[varargin{i} '_subfields']) &&
    ~isempty(dat.([varargin{i} '_subfields']))
![image](https://user-images.githubusercontent.com/58855350/134381610-db1c5d1a-28fd-41b7-b801-8b1f856476f8.png)

**Comment by foudasarah** [comment]
I also runed the Rrun,R and installed R package.

**Comment by foudasarah** [comment]
And the error appears at the Rpull function

**Comment by foudasarah** [comment]
Thank you !

**Comment by JanineEgert** [comment]
Hi Sarah, 
it looks like the problem goes into your PATH environment variables. Did you try opening R and Matlab in your terminal? Maybe check the path by 'which' or 'where' (windows). We can also chat per skype 'Janine E' if you can not manage opening the R/Matlab instances.
Best,
Janine

**Comment by foudasarah** [comment]
Hello. I tried with an other device I get this issue : at the same place (Rpull) 
The filename, directory name, or volume label syntax is incorrect. 
The filename, directory name, or volume label syntax is incorrect. 
Warning: Is the R package installed? Try to run Rrun.R in R for error prouning. 
> In Rpull (line 51) 
Unrecognized function or variable 'dat'.

Error in Rpull (line 56)
    if isfield(dat,[varargin{i} '_subfields']) && ~isempty(dat.([varargin{i}
    '_subfields']))

I will try to figure out what is going on. And let you kmow I think I did something not good 
thank you

**Comment by JanineEgert** [comment]
This is the same issue of the system not finding the R executable. If so, try to add the R path to your system environmental variable, or define the R path in the Rinit function as second input argument ```Rinit([],'C:\Program Files\R\R-4.1.0\bin\R.exe')```

**Comment by JanineEgert** [comment]
Setting the R path solved the problem on both machines
