### ISSUE TITLE
R engine instantiated

### ISSUE THREAD

**Issue by mbanco** [kreutz-lab/Rcall#3]
Is it possible to keep R engine instantiated, so that other functions can be called later, using variables stored in the global environment?

Best regards.

Mauricio

**Comment by JanineEgert** [comment]
Dear Mauricio,

the variables are temporary and cleared with the Rclear command. If you do not clear the workspace, the variables can be used repeatedly. Example: 
Rinit
Rpush('dat',zeros(3,3))
Rrun('dat1 <- dat+1')
dat1 = Rpull('dat1');

You can reuse the variable **dat** which is stored in the MATLAB workspace **Rpush.mat**
Rrun('dat2 <- dat+2')
dat2 = Rpull('dat2')

To reuse the variable **dat1**, use the **Rpush** command:
Rpush('dat1',dat1)
Rrun('dat3 <- dat1+2')
dat3 = Rpull('dat3');

Rclear

Best,
Janine

**Comment by mbanco** [comment]
Thanks Janine.

Mauricio.
