### ISSUE TITLE
myLibPaths vs myLibPath

### ISSUE THREAD

**Issue by apkaye** [kreutz-lab/Rcall#5]
Hi,

It looks like there might be a small typo on line 95 of Rexe.m. 

As far as I can tell the global for the library path is myLibPath everywhere else in the code. On line 95 it is referenced as myLibPath**s** 

![Screen Shot 2022-05-17 at 6 11 14 PM](https://user-images.githubusercontent.com/12899172/168919474-0194e736-9258-4308-9512-cdfb29de5432.png)

**Comment by clemenskreutz** [comment]
Thanks for this hint. I updated the code accordingly.
