### ISSUE TITLE
Trouble with example code

### ISSUE THREAD

**Issue by apkaye** [kreutz-lab/Rcall#6]
Hello,

Thank you for sharing this package! I'm having some trouble with some simple example code. My code and the output are below. I'm using Matlab R2021a and R 4.2.0.  Do you have any suggestions?

![image](https://user-images.githubusercontent.com/12899172/169094156-0e3637b7-7135-4751-83cb-141233268b14.png)
![image](https://user-images.githubusercontent.com/12899172/169094170-9b80e494-4002-42c8-bc3e-dcb871cc1165.png)

I think the R path is correct - that folder exists. Here are the contents of `/Library/Frameworks/R.framework/Resources/`
![image](https://user-images.githubusercontent.com/12899172/169094196-8e7fcc88-02a5-4f4c-b2cf-cc9674f22064.png)

**Comment by clemenskreutz** [comment]
I have made an attempt to solve this issue. Please update the code and check again.

**Comment by apkaye** [comment]
Hi,

Thank you for the quick response! I'm getting a new error:
<img width="1049" alt="Screen Shot 2022-05-18 at 2 44 02 PM" src="https://user-images.githubusercontent.com/12899172/169122219-8791c8ec-40c9-46d6-8f1d-816da027b03e.png">

**Comment by clemenskreutz** [comment]
Can you check, whether the command printed in the message "/Library/Framework/R.framework/Resources/R" CMD BATCH --slave "/Users/aaronkaye/Documents/EconResearch/Expedia/Analysis/matlab/Rrun.R" works when you paste this to the command line (e.g. bash/shell/Windows Command Prompt)? 

How do you have to change the command in order to get it run?

Which operating system do you use?

**Comment by apkaye** [comment]
hi - I am getting an error  `no such file directory`

I'm using a mac with version 12.3.1. 

<img width="561" alt="Screen Shot 2022-05-19 at 10 43 06 AM" src="https://user-images.githubusercontent.com/12899172/169323913-9b32a5f1-664f-4acb-bb6d-6b48ebeb3a16.png">

 the file directory obviously exists though.
![Screen Shot 2022-05-19 at 11 29 17 AM](https://user-images.githubusercontent.com/12899172/169336402-c909390f-1a33-4c8c-9a74-02bd1fe86687.png)

**Comment by clemenskreutz** [comment]
Maybe it is a problem that "R" is an "Alias", i.e. shortcut (see screenshot above). 
Maybe you try to call the target of the Alias directly?

**Comment by apkaye** [comment]
Thanks again for the help.

Okay - I update the file path for R, seems like `'/usr/local/bin/R'` or `'/Library/Frameworks/R.framework/Versions/4.2/Resources/bin/R'` get me further. I'm getting the following error in the command line:


```
MacBook-Pro:/ aaronkaye$ "/Library/Frameworks/R.framework/Versions/4.2/Resources/bin/R" CMD BATCH --slave "/Users/aaronkaye/Documents/Econ Research/Expedia/Analysis/matlab/Rrun.R"

/Library/Frameworks/R.framework/Resources/bin/BATCH: line 60: Econ
Rrun.R
.R.Rout: Read-only file system
```

**Comment by apkaye** [comment]
Hi Again,

I think there is a bug dealing with file paths that have a spaces.  My current directory (in matlab) is 

`/Users/aaronkaye/Documents/Econ Research/Expedia/Analysis/matlab`

If I remove the spaces, Rcall now works. Here is the error that tipped me off:

![Screen Shot 2022-05-20 at 2 43 37 PM](https://user-images.githubusercontent.com/12899172/169592481-dd63278d-aa4c-4f4c-8e0e-da28ccc128d5.png)
